package ua.omniway.models.rest;

public enum ServiceCallEvent {
    SR_SOLUTION_WITH_CONFIRMATION,
    INC_SOLUTION_WITH_CONFIRMATION,
    INTERACT_TO_CALLER,
    INTERACT_TO_RESPONSIBLE,
    SR_REGISTERED,
    INC_REGISTERED,
    CR_REGISTERED,
    SR_SOLUTION,
    INC_SOLUTION,
    CR_SOLUTION;
}