
package ua.omniway.client.ot.soap.service;

import ua.omniway.client.ot.soap.*;
import ua.omniway.client.ot.soap.GetObjectListData;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 */
@WebService(name = "OTWebServiceSoap", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface OTWebServiceSoap {


    /**
     * @param object
     * @return returns ua.omniway.soap.AddObjectResult
     */
    @WebMethod(operationName = "AddObject", action = "http://www.omninet.de/OtWebSvc/v1/AddObject")
    @WebResult(name = "AddObjectResult", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
    @RequestWrapper(localName = "AddObject", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.AddObject")
    @ResponseWrapper(localName = "AddObjectResponse", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.AddObjectResponse")
    public AddObjectResult addObject(
            @WebParam(name = "Object", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    AddObjectData object);

    /**
     * @param object
     * @return returns ua.omniway.soap.ModifyObjectResult
     */
    @WebMethod(operationName = "ModifyObject", action = "http://www.omninet.de/OtWebSvc/v1/ModifyObject")
    @WebResult(name = "ModifyObjectResult", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
    @RequestWrapper(localName = "ModifyObject", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.ModifyObject")
    @ResponseWrapper(localName = "ModifyObjectResponse", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.ModifyObjectResponse")
    public ModifyObjectResult modifyObject(
            @WebParam(name = "Object", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    ModifyObjectData object);

    /**
     * @param useTrashbin
     * @param ignoreReferences
     * @param objectID
     * @return returns ua.omniway.soap.RemoveObjectResult
     */
    @WebMethod(operationName = "RemoveObject", action = "http://www.omninet.de/OtWebSvc/v1/RemoveObject")
    @WebResult(name = "RemoveObjectResult", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
    @RequestWrapper(localName = "RemoveObject", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.RemoveObject")
    @ResponseWrapper(localName = "RemoveObjectResponse", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.RemoveObjectResponse")
    public RemoveObjectResult removeObject(
            @WebParam(name = "ObjectID", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    int objectID,
            @WebParam(name = "UseTrashbin", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    boolean useTrashbin,
            @WebParam(name = "IgnoreReferences", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    boolean ignoreReferences);

    /**
     * @param script
     * @return returns ua.omniway.soap.InvokeScriptResult
     */
    @WebMethod(operationName = "InvokeScript", action = "http://www.omninet.de/OtWebSvc/v1/InvokeScript")
    @WebResult(name = "InvokeScriptResult", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
    @RequestWrapper(localName = "InvokeScript", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.InvokeScript")
    @ResponseWrapper(localName = "InvokeScriptResponse", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.InvokeScriptResponse")
    public InvokeScriptResult invokeScript(
            @WebParam(name = "Script", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    InvokeScriptParameters script);

    /**
     * @param get
     * @return returns ua.omniway.soap.GetObjectListResult
     */
    @WebMethod(operationName = "GetObjectList", action = "http://www.omninet.de/OtWebSvc/v1/GetObjectList")
    @WebResult(name = "GetObjectListResult", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
    @RequestWrapper(localName = "GetObjectList", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.GetObjectList")
    @ResponseWrapper(localName = "GetObjectListResponse", targetNamespace = "http://www.omninet.de/OtWebSvc/v1", className = "ua.omniway.soap.GetObjectListResponse")
    public GetObjectListResult getObjectList(
            @WebParam(name = "Get", targetNamespace = "http://www.omninet.de/OtWebSvc/v1")
                    GetObjectListData get);

}
